### ISSUE TITLE
stack

### ISSUE THREAD

**Issue by ichijoraku** [adrianonrails/baruch#17]
stack/ white screen.

**Comment by adrianonrails** [comment]
What screen? Checked the app, there is a display.
![image](https://user-images.githubusercontent.com/18593260/36196717-933238aa-11ac-11e8-830f-73613dd9b969.png)

**Comment by ichijoraku** [comment]
mine will  stuck in whitescreen when I ran the app.

**Comment by ichijoraku** [comment]
Im using 4.2.2.. T_T

**Comment by ichijoraku** [comment]
screen size 320x480

**Comment by adrianonrails** [comment]
Currently ionic3 (framework used in this project) supports 4.4 and up. Adding support for 4.2.2 will make the app heavier. I'll try to make an isolated release for these kind of android versions.

**Comment by adrianonrails** [comment]
You may now download the release that will support your android version.
[https://github.com/adrianonrails/baruch/releases/download/v0.8.9b/Baruch_crosswalk.apk](https://github.com/adrianonrails/baruch/releases/download/v0.8.9b/Baruch_crosswalk.apk) 

Do note that the file size of the apk is now >50mb rather than the original <9mb. It is because of the added crosswalk.
